### ISSUE TITLE
Set Asset ID not Working

### ISSUE THREAD

**Issue by GameEnder** [iamtheyammer/gam-cros-win-wrapper#13]
The "annotatedAssetId" never gets updated works fine in Google Admin and in GAM terminal.

**Comment by iamtheyammer** [comment]
Seems to be working okay for me. Are you pressing the "clear asset id" button? that's #14 and I'm working on that.

**Comment by iamtheyammer** [comment]
In the last comment, I was using my latest code. In the current release version, yeah, it seems to be setting it to "Test location"

**Comment by iamtheyammer** [comment]
Okay, did more testing. It's working fine for me. Is your GAM version as new as it can be? 4.6.5 is what 0.2.8 should run on.

**Comment by GameEnder** [comment]
Am on GAM 4.65. Changing the Asset ID works fine from GAM terminal.

**Comment by iamtheyammer** [comment]
Can I ask what type of data you put in the search bar? (email/serial number/asset id/query string)?

**Comment by GameEnder** [comment]
Serial Number

**Comment by iamtheyammer** [comment]
OK, and if you press get info do you get info? Also, what version of the app are you on? (Help -> Check for updates)

**Comment by iamtheyammer** [comment]
Ok, in this case I'd like to recommend you update to the latest alpha build, which is currently v0.2.8. 

One thing about the alpha build: you'll need to uninstall your current version of ChromebookGUI before installing the new alpha. (start menu, type "appwiz.cpl", double click on the program and uninstall it) 

The alpha installer link is [here](https://github.com/iamtheyammer/gam-cros-win-wrapper/raw/master/ChromebookGUI/Installer/Tool+Installer/Installer.msi).

**Comment by GameEnder** [comment]
Yep that fixed it. Guess I just wasn't updating.
