### ISSUE TITLE
appears to not be working with GAM 4.72 

### ISSUE THREAD

**Issue by matt199x** [iamtheyammer/gam-cros-win-wrapper#16]
Appears to not be working with GAM 4.72 just closes right away when I click submit

**Comment by matt199x** [comment]
This might actually be an environment variable issue on my end. Looking into it

**Comment by iamtheyammer** [comment]
This seems like it can’t find the GAM executable. If you open event viewer (run: eventvwr), you’ll see a .NET application error. Take a screenshot of the error details and upload them here.

**Comment by matt199x** [comment]
I got it working. I had to add an environment variable and put gam in a folder other than system32 for some reason.
