### ISSUE TITLE
Alpha 1.0.4 - "Update available" popup

### ISSUE THREAD

**Issue by msd-rjoachim** [iamtheyammer/gam-cros-win-wrapper#17]
![image](https://user-images.githubusercontent.com/33043645/57241734-82da0c00-6fe6-11e9-90e2-db87418b8d50.png)

Looks like there needs to be more differentiation between the stable version and all others, so that alpha/beta versions don't see the lower version as an update.

**Comment by iamtheyammer** [comment]
That's a pre-pre-prerelease so it's not an official alpha yet. Also I just updated the app to 1.0.5, downloadable [here](https://github.com/iamtheyammer/gam-cros-win-wrapper/raw/v1-0/ChromebookGUI/Installer/Tool%2BInstaller/Installer.msi).

**Comment by iamtheyammer** [comment]
Try doing Ctrl+L in that version too

**Comment by msd-rjoachim** [comment]
I'm just diving back into this today - been away at a conference since last week. I'll grab the latest release.

Ctrl+L puts focus in the main textbox. Nice feature to have.

**Comment by msd-rjoachim** [comment]
The alpha version is still showing as 1.0.4 (updated 20 hours ago).

**Comment by iamtheyammer** [comment]
This has been fixed with the public release of 1.0.10.
