### ISSUE TITLE
Alpha 1.0.4 (Suggestion) - Split update functions apart

### ISSUE THREAD

**Issue by msd-rjoachim** [iamtheyammer/gam-cros-win-wrapper#20]
It might be more flexible to separate the field update triggers from each other.
Currently, **Location, User, and Note** are all updated at the same time, whether the field has been modified or was already empty.

If a field is already empty, it should be ignored and not resubmitted.
If a field has not been modified, it should be ignored.

See https://github.com/iamtheyammer/gam-cros-win-wrapper/issues/19 for an example of the issue.

**Comment by iamtheyammer** [comment]
The fix in #19 applies here, as well. Fixed, waiting for commit.
