### ISSUE TITLE
Alpha 1.0.4 (Suggestion) - Windows and prompts don't follow the GUI positioning

### ISSUE THREAD

**Issue by msd-rjoachim** [iamtheyammer/gam-cros-win-wrapper#21]
Sub-windows (progress bar, confirmation/warning prompts) ignore current position of the main GUI. If the GUI is moved anywhere (even to a different monitor), the prompts stay in the initial position.

Prompts/Windows also ignore manual positioning for subsequent prompts (you can drag the prompt to where you want while it is active, but future prompts reset to their original position).

**Comment by iamtheyammer** [comment]
Fixed. Now, all windows spawned by the app will be centered in the main window. I'll wait until the commit to close this.
