### ISSUE TITLE
Clear default text from Omnibar when selected

### ISSUE THREAD

**Issue by msd-rjoachim** [iamtheyammer/gam-cros-win-wrapper#23]
**Additional context**
![image](https://user-images.githubusercontent.com/33043645/58727781-1e6a5c80-839a-11e9-9bd2-cf74fbd673f6.png)

The default description in the Omnibar is currently treated as normal text, which means you have to either overwrite it or delete it before moving forward. For usability and improving the workflow, the bar should clear out on the initial selection (per instance of the GUI).

Similarly, the Output box should be read-only. Right now the results are editable (you can delete, move, space, etc), which isn't really a problem but doesn't seem to serve a purpose specifically.

**Comment by iamtheyammer** [comment]
## Initial text
I'll see if I can make this placeholder text, but if not, I'll make it auto clear on click.

## Output box writability
This was initially done because I wanted to be able to select text inside. I could interrupt KeyUp events but I just don't see a reason to.

**Comment by iamtheyammer** [comment]
Fixed this in 1.0.11
