### ISSUE TITLE
Improve Omnibar text interaction

### ISSUE THREAD

**Issue by msd-rjoachim** [iamtheyammer/gam-cros-win-wrapper#24]
**Describe the solution you'd like**

See if there is a simple way of improving the highlighting behavior in the Omnibar. Right now you can single-click to choose the insert point, but trying to click again (either to move the insert to another spot, or to try highlighting just a section of the text) selects the entire textbox. You can then "reduce" the highlight from the left or the right, but it's not intuitive.
![image](https://user-images.githubusercontent.com/33043645/58728472-d1878580-839b-11e9-9160-e9865ea0df6b.png)

**Comment by iamtheyammer** [comment]
This was built before autocorrect and, yeah, it's unintuitive now. I'll remove it in the next release.

**Comment by iamtheyammer** [comment]
Fixed in 1.0.11
