### ISSUE TITLE
[BUG] "Update available" link needs to be updated

### ISSUE THREAD

**Issue by msd-rjoachim** [iamtheyammer/gam-cros-win-wrapper#29]
**Describe the bug**

"Update available" prompt sends users to the old link location.

> https://github.com/iamtheyammer/gam-cros-win-wrapper/raw/master/ChromebookGUI/Installer/Tool+Installer/Installer.msi

**Comment by iamtheyammer** [comment]
Yup oops. I'll make this part of the releases.json file, but only the path after https://github.com/iamtheyammer/gam-cros-win-wrapper for security

**Comment by iamtheyammer** [comment]
Is this an issue in 1.0.11 or just 1.0.10? Because Updates.cs has it going to the right place. https://github.com/iamtheyammer/gam-cros-win-wrapper/blob/master/ChromebookGUI/ChromebookGUI/Classes/Updates.cs#L76

**Comment by msd-rjoachim** [comment]
I was on 1.0.10 when I saw the popup for 1.0.11. The link from there took me to where I posted above.

**Comment by iamtheyammer** [comment]
Yeah ok this is fixed in 1.0.11. I'll make the path dynamic in 1.0.12

**Comment by iamtheyammer** [comment]
I decided that I'm going to change the structure of the updates in the next version (1.1.0). 

p.s. you'll enjoy that the text box view is 2x faster

**Comment by iamtheyammer** [comment]
Closed as I just released Alpha v1.1.0

**Comment by msd-rjoachim** [comment]
"Download newest build" button (after reinstalling the newest alpha) takes me to a 404 page (https://github.com/iamtheyammer/releases/latest).

**Comment by iamtheyammer** [comment]
I’ll look into this

**Comment by iamtheyammer** [comment]
You mentioned "after reinstalling the newest alpha"-- what version is that?

**Comment by msd-rjoachim** [comment]
The installer (and installed version) both show 1.0.11.

**Comment by msd-rjoachim** [comment]
Downloaded the latest Alpha (v1.0.10) and so far no update nag. I'll keep an eye on it with the next release.

**Comment by iamtheyammer** [comment]
Ok, cool. I'm going to close this issue in that case. Please reopen it if it reoccurs.
