### ISSUE TITLE
[I/C] Latest version number mismatch

### ISSUE THREAD

**Issue by msd-rjoachim** [iamtheyammer/gam-cros-win-wrapper#30]
Sorry you encountered an error or a crash. Thank you for helping out ChromebookGUI.

**Describe the issue**
![2019-06-06_14-12-24](https://user-images.githubusercontent.com/33043645/59067156-bc13cf00-8865-11e9-9f10-652cb02a361a.png)

Currently installed version is 1.0.11 (reinstalled from the latest available). 
Latest MSI on Github is labeled 1.0.11.
The most recent release notes have the 1.0.10 tag, so maybe that's where the problem is coming from.

**Comment by iamtheyammer** [comment]
Seems linked to #29

**Comment by iamtheyammer** [comment]
The release for Alpha 1.1.0 is here. This was caused by me using the releases/latest URL which doesn't go to prereleases.

I'll fix this in the gh-pages branch.
