### ISSUE TITLE
[I/C] Omnibar dropdown persists while text is in the box

### ISSUE THREAD

**Issue by msd-rjoachim** [iamtheyammer/gam-cros-win-wrapper#31]
Thanks for helping improve ChromebookGUI!

**Describe the bug**
Omnibar dropdown persists while text is in the box. Once text is removed, the dropdown disappears as well. Using Alpha 1.0.10 (latest).

**To Reproduce**
Type anything into the search bar and then try to access items behind the dropdown.

**Screenshots**
![image](https://user-images.githubusercontent.com/33043645/59305066-51400a80-8c4e-11e9-9bcc-b638a2d62fed.png)

**Comment by iamtheyammer** [comment]
This is expected behavior-- you can click on autocompletions when they're present.

Press escape to close the autocomplete area.
