### ISSUE TITLE
'Enable' doesn't seem to be working

### ISSUE THREAD

**Issue by msd-rjoachim** [iamtheyammer/gam-cros-win-wrapper#5]
I can find the devices I want using asset ID or something like that. The information for the devices is shown in the results window.

Clicking on 'Enable' doesn't enable the device. All I see is - "As long as you don't see an error, this query completed successfully." Clicking 'Disable' shows the deviceID below and works like it should.

I can enable manually with GAM, or by using the deviceID to search with. 
It seems to not pull the deviceID when searching with something _other than_ the deviceID.

**Comment by iamtheyammer** [comment]
This issue was addressed in the newest commit. The newest build can be downloaded [here](https://github.com/iamtheyammer/gam-cros-win-wrapper/raw/master/ChromebookGUI/ChromebookGUI/bin/Release/ChromebookGUI.exe).
