### ISSUE TITLE
Set Location - automatically clear textbox on select, and allow for blank entry.

### ISSUE THREAD

**Issue by msd-rjoachim** [iamtheyammer/gam-cros-win-wrapper#8]
Both of these could be tagged as "improvements". There are times (many times, for my environment) where an old standard had data put into the Location field - now that we don't use this field anymore, it would be great to be able to clear out the text box and submit it just to clear out the field on the device. 

Maybe a separate box within the popup to "clear current text"?

**Comment by iamtheyammer** [comment]
Sure, I'll do that for location and Asset ID.

**Comment by iamtheyammer** [comment]
Cool, this is done and is available from the new [Alpha 0.2.1](https://github.com/iamtheyammer/gam-cros-win-wrapper/raw/master/ChromebookGUI/Installer/Tool+Installer/Installer.msi). <- That link will download the new installer.
