### ISSUE TITLE
Alpha 0.2.1 - Clear Location button present, but not working.

### ISSUE THREAD

**Issue by msd-rjoachim** [iamtheyammer/gam-cros-win-wrapper#9]
Message received - 

> 
> GAM 4.61 - https://git.io/gam
> Jay Lee <jay0lee@gmail.com>
> Python 2.7.15 32-bit final
> google-api-python-client 1.7.3
> oauth2client 4.1.2
> Windows-10-10.0.17134 AMD64
> Path: C:\GAM
> 
> Usage: gam [OPTIONS]...
> 
> GAM. Retrieve or set G Suite domain,
> user, group and alias settings. Exhaustive list of commands
> can be found at: https://github.com/jay0lee/GAM/wiki
> 
> Examples:
> gam info domain
> gam create user jsmith firstname John lastname Smith password secretpass
> gam update user jsmith suspended on
> gam.exe update group announcements add member jsmith
> ...
> 
> 
> As long as you don't see an error, the location has been updated.

It seems like it's trying to send - 
`gam update cros DeviceId location ` (blank space at the end), 
instead of - `gam update cros DeviceId location ""`. 
Verified that manually using the second option works as expected, while the first gives the same result as above.

The Clear Asset ID button is working as expected.

**Comment by iamtheyammer** [comment]
Fixed in Alpha v0.2.2. I made sure and went through and tested, both are working.

Also, it will save them in memory so if you go change it later it will have the previous value.
